---
included:
  - GEOSwift
  - GEOSwiftTests
excluded:
  - GEOSwiftTests/XCTestManifests.swift
disabled_rules:
  - force_cast
  - identifier_name
  - type_name
  - no_space_in_method_call  # https://github.com/realm/SwiftLint/issues/2793
opt_in_rules:
  - closure_spacing
  - empty_count
  - implicit_return
  - pattern_matching_keywords
  - vertical_parameter_alignment_on_call
line_length: 110
